language: php
php:
  - 5.3
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
 - cd ../..
 - mysql -e 'create database drupal;'
 - pear channel-discover pear.drush.org
 - pear install drush/drush-5.8.0
 - phpenv rehash
 - drush dl --yes drupal
 - cd drupal-*
 - pwd
 - ls -lah ../
 - mv ../andytruong/at_config sites/all/modules/
 - echo '#####################'
 - echo 'Clone required libraries'
 - echo '#####################'
 - mkdir -p sites/all/libraries
 - cd sites/all/libraries
 - composer require mustangostang/spyc:0.5.*
 - mv vendor/mustangostang/spyc ./
 - rm -rf ./vendor composer.*
 - cd ../../..
 - echo '#####################'
 - echo 'Install Drupal - Enable modules'
 - echo '#####################'
 - drush si testing --db-url=mysql://root:@localhost/drupal --yes
 - drush en --yes simpletest at_route
 - drush cc all
 - sleep 3

script: drush test-run 'AT Config'
