<?php

use \Drupal\at_config\Resolver;
use \Drupal\at_config\Config;

/**
 * Usage
 *
 * // Lookup at /path/to/my_module/config/config.yml > webmaster
 * $webmaster_email = at_config('my_module')->get('webmaster');
 *
 * // Lookup at /path/to/my_module/config/templates.yml > email.notify
 * $mail_notify_template = at_config('my_module', 'templates')->get('email.notify');
 *
 * @param  string  $module    Module name
 * @param  string  $id        Config ID
 * @param  boolean $refresh   Build new cache
 * @return Config
 * @todo   Will remove when at_di.module is ready.
 */
function at_config($module, $id = 'config', $refresh = FALSE) {
  $resolver =  new Resolver();
  return new Config($module, $id, $resolver);
}

/**
 * Read YAML file.
 *
 * @param  string $path Path to yaml file.
 * @return mixed
 */
function at_config_read_yml($path) {
  require_once DRUPAL_ROOT . '/sites/all/libraries/spyc/Spyc.php';
  return spyc_load_file($path);
}
