<?php

/**
 * Usage
 *
 * // Lookup at /path/to/my_module/config/my_module.yml > webmaster
 * $webmaster_email = at_config('%my_module%')->get('webmaster');
 *
 * // Lookup at /path/to/my_module/config/templates.yml > email.notify
 * $mail_notify_template = at_config('%my_module%.templates')->get('email.notify');
 *
 * @param  string  $id      Config ID
 * @param  boolean $refresh Build new cache
 * @return \Drupal\at_config\Config
 */
function at_config($id, $refresh = FALSE) {
  $options['ttl'] = '+ 15 minutes';
  $options['cache_id'] = "at_config:{$id}";
  return go_cache($options, function() use ($id) {
    return go_id(new \Drupal\at_config\Resolver($id))->getConfigObject();
  });
}
